### PR TITLE
Release 2: Prefix variables, README cleanup, copy template to destination

### PR DESCRIPTION
**Pull request by hansmi**
This series of changes bring significant changes which will require a new major version number. Leftovers from before the conversion to an Ansible role are removed (and only usage as an Ansible role is supported anymore). All role parameters have been prefixed with `appuio_gluster_recycler_` as to not conflict with other variables and other minor changes have been made (see `README.md` and `defaults/main.yml`). The role now supports being instantiated on a remote host.

### CODE REVIEW

**Comment by dtschan** [comment]
The automatic variables role_version and role_src, set by the role invocation logic, must not be removed from the defaults or it will require redundant configuration on our setups.

**Comment by hansmi** [comment]
> The automatic variables role_version and role_src, set by the role invocation logic, must not be removed from the defaults or it will require redundant configuration on our setups.

You can set `appuio_gluster_recycler_repo: "{{ repo_src }}"` and `appuio_gluster_recycler_repo_rev: "{{ repo_version }}"` (see below for `_rev`) in your inventory, or via variables in case your setup uses [`include_role`](https://docs.ansible.com/ansible/latest/include_role_module.html). A new major number signifies breaking changes.

I'll rename `appuio_gluster_recycler_repo_tag` to `appuio_gluster_recycler_repo_rev` to match the Git terminology.

**Comment by dtschan** [comment]
Ok, I guess we can live with that. But we'll have to discuss the prefixing of the role parameters. I'm not sure whether this is really needed and readability suffers greatly.

**Comment by hansmi** [comment]
> But we'll have to discuss the prefixing of the role parameters. I'm not sure whether this is really needed and readability suffers greatly.

In our setup we use a global inventory and variable names obviously can't overlap/conflict. My changes are designed after openshift-ansible (i.e. [`roles/openshift_metrics/defaults/main.yaml`](https://github.com/openshift/openshift-ansible/blob/openshift-ansible-3.7.0-0.125.0/roles/openshift_metrics/defaults/main.yaml)). We could probably drop the `appuio_` prefix, but I rather have some sort of variable namespace per project, which would be `appuio_gluster_recycler_`. Roles are free to set variables with shorter names, though it's not necessary for this role and conflicts must still be avoided. Example:
```yaml
- set_fact:
    role_rev: "{{ appuio_gluster_recycler_repo_rev }}"

- debug:
    msg: "{{ role_rev }}"
```

**Comment by dtschan** [comment]
I agree that inventory variables must be prefixed. We too are using a global inventory but currently configure roles like this:

```yaml
 appuio_ansible_post_install_roles:
  - name: gluster-recycler
    src: https://github.com/appuio/gluster-recycler
    scm: git
    version: v1.1.2
    vars:
      gluster_hosts: host1.example.org,host2.example.org,host3.example.org
      delay: "{{ 7 * 24 * 60 * 60 }}"  # 7 days
```

How about keeping the current parameter names and using defaults like `"{{ appuio_gluster_recycler_namespace | default('appuio-infra') }}"`? This would support both inventory styles and maintain backwards compatibility.

**Comment by hansmi** [comment]
> We too are using a global inventory but currently configure roles like this: […]

Unfortunately that requires setting the variables every time a role is used. I already know that we'll have to use the same role in multiple places and would very much like to avoid repeating the parameters (even if they're nothing more than a re-assignment from global parameters).

> How about keeping the current parameter names and using defaults like "{{ appuio_gluster_recycler_namespace | default('appuio-infra') }}"?

Defaults are used, see `defaults/main.yaml`. These would obviously be a pain to repeat everywhere. Excerpt:
```yaml
appuio_gluster_recycler_namespace: appuio-infra
appuio_gluster_recycler_repo: https://github.com/appuio/gluster-recycler.git
[…]
```

I consider the unprefixed variables too dangerous to retain. Maybe not with this role, but others are or will be composited of multiple small (utility) roles. Consider this untested code:

```yaml
# Role has a parameter variable named "svcdir"

- set_fact:
    home: "{{ svcdir }}/home"

- include_role: other-role

- file:
    path: "{{ home }}"
    state: absent
```

This will work as intended until `other-role` decides to set `home` to another value, i.e. `/`. That can be never or in half a year. Of course no technical mechanism prevents `other-role` from setting `appuio_gluster_recycler_svcdir`, but it'll much more obvious.

**Comment by dtschan** [comment]
Note sure if we have our wires crossed. But my proposal allows both of us to keep our respective inventories for the time being. Also the defaults wouldn't have to be repeated as they are configured in defaults/main.yml. As far as I see the example you give has nothing to do with role parameters, which are scoped per role.

**Comment by hansmi** [comment]
> But my proposal allows both of us to keep our respective inventories for the time being. Also the defaults wouldn't have to be repeated as they are configured in defaults/main.yml. As far as I see the example you give has nothing to do with role parameters, which are scoped per role.

The latter applies if and only if you're setting the parameters when invoking the roles. We're not doing that, though. We're applying roles like this in a playbook while all configuration is in a single inventory:
```
- hosts: masters[0]
  gather_facts: false
  roles:
    - gluster-recycler
```
We could implement your proposal and change the default for, say, the namespace to `appuio_gluster_recycler_namespace: "{{ namespace | default('appuio-infra') }}"`. Old-style invocations with `namespace` instead of `appuio_gluster_recycler_namespace` will keep working. That is until another role is applied first which uses `namespace` internally (this is what I tried to show in my example), i.e.:
```
- hosts: OSEv3
  gather_facts: false
  roles:
    # Uses "namespace" internally
    - openshift-foobar

- hosts: masters[0]
  gather_facts: false
  roles:
    - gluster-recycler
```
This case would us to explictly (re)set `namespace` when invoking `gluster-recycler` (`null` is untested; may need an explicit value):
```
- hosts: masters[0]
  gather_facts: false
  roles:
    - gluster-recycler
  vars:
    namespace: null
```
Would you agree that unless deliberately designed that way the "internal" (non-prefixed) variables of one role shouldn't affect the behaviour of another role, and even less so should the order in which they're applied?

**Comment by dtschan** [comment]
I analysed why we don't see the behaviour you describe. In our setup variables in roles don't affect the calling playbook or other roles. Here's what I found out:

* Ansible 2 introduced private role variables, but they are disabled by default in order to have backwards compatible behaviour with Ansible 1: https://github.com/ansible/ansible/issues/12081
* Roles included with `include_role` always have private variables. The private attribute of `include_role` is ignored: https://github.com/ansible/ansible/issues/21890
* It's irrelevant whether role parameters are set on invocation or via playbook or inventory variables.
* Facts, including registered variables, are always global (that much was clear already and is documented accordingly in the Ansible docs).

Since we only use `include_role` to load roles, role variables are private in our setup.

So this leaves us with three options:

1. Prefix all variables
2. Always load roles with `include_role` and `private: True`.
3. Enable private role variables in `ansible.cfg`.

Global variables like facts and registered variables must always be prefixed.

All options have some issues:
Option 1: It's easy to forget to prefix a variable and third party roles often have unprefixed variables.
Option 2: Variables can conflict when a role is loaded through `roles` instead of `include_role`.
Option 3: Can cause playbooks which expect Ansible 1 behaviour to fail.

Option 3 is obviously most problematic. I lean toward option 2 since it also works with third party roles, is easier to enforce than option 1 and is the behaviour you're accustomed from programming languages. However if you still want to use option 1 I'll merge the request and we'll stay on 1.x of the recycler for the time being.

For option 2 I'd change the `defaults/main.yml` like this, so that it would also work with your inventory:

```yaml
namespace: "{{ appuio_gluster_recycler_namespace | default('appuio-infra') }}"
src: "{{ appuio_gluster_recycler_repo | default('https://github.com/appuio/gluster-recycler.git') }}"
version: "{{ appuio_gluster_recycler_repo_rev | default('master') }}"
gluster_hosts: "{{ appuio_gluster_recycler_gluster_hosts | mandatory }}"
interval: "{{ appuio_gluster_recycler_interval }}"
delay: "{{ appuio_gluster_recycler_delay | default(0) }}"
timezone: "{{ appuio_gluster_recycler_timezone | default(appuio_container_timezone) | default('UTC') }}"
```

**Comment by hansmi** [comment]
I'm sorry for taking such a long time to respond. I wasn't aware of `private`--thanks for the research!

> Option 1: It's easy to forget to prefix a variable and third party roles often have unprefixed variables.

I have to agree with this, though prefixes are merely a conflict-avoiding measure, not prevention (`private` aside).

> Always load roles with `include_role` and `private: True`.

We currently don't use `include_role` and instead pull roles into playbooks (see my September 11, 2017 comment), but we might need to use `include_role` at in the future. It'd be quite a significant change and one would have to be careful to apply it everywhere.

> Option 3: Can cause playbooks which expect Ansible 1 behaviour to fail.

Yes, this is not good. We shouldn't change a global setting with such an impact.

> However if you still want to use option 1 I'll merge the request and we'll stay on 1.x of the recycler for the time being.

All in all I still prefer option 1, yes.

To help with your environment: Would you like me to write a wrapper role taking the old parameters and passing them to `gluster-recycler` with prefixes?

**Comment by dtschan** [comment]
A wrapper role is not required, thanks. I'll upgrade clusters to the new version the next time I touch their recyclers, either by changing the inventory or by implementing prefix support into our role inclusion logic.

**Pull request merged**
